apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-reader
  namespace: rds-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-reader
  template:
    metadata:
      labels:
        app: backup-reader
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
  - name: backup-reader
    image: alpine@sha256:47c8b2a5a0f9d0f50f9a92cde157b7f52a504d9f68593c709f013bc3b8df5c92
    imagePullPolicy: Always
    command: ["/bin/sh", "-c", "sleep infinity"]
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "64Mi"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: gitlab-backup-volume
        mountPath: /mnt/backup
    livenessProbe:
      exec:
        command: ["cat", "/proc/self/status"]
      initialDelaySeconds: 10
      periodSeconds: 20
    readinessProbe:
      exec:
        command: ["cat", "/proc/self/status"]
      initialDelaySeconds: 5
      periodSeconds: 10

      volumes:
        - name: gitlab-backup-volume
          persistentVolumeClaim:
            claimName: gitlab-backup-pvc
