---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: rds-git
automountServiceAccountToken: true


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-node-access
rules:
  - verbs:
      - get
      - list
    apiGroups: [""]
    resources: ["nodes"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rds-git-node-access
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: rds-git
roleRef:
  kind: ClusterRole
  name: prometheus-node-access
  apiGroup: rbac.authorization.k8s.io
